[package]
name = "slog2-types"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Common types that are used by ther slog2 crates."
repository = "https://github.com/mounten/slog2"

[dependencies]
bitflags = "2.9.4"
